import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core';
import { categories } from './categories';

export const categoryRules = sqliteTable('category_rules', {
  id: text('id').primaryKey(),
  pattern: text('pattern').notNull(),
  categoryId: text('category_id')
    .notNull()
    .references(() => categories.id, { onDelete: 'cascade' }),
  matchType: text('match_type', {
    enum: ['contains', 'starts_with', 'regex', 'exact'],
  })
    .notNull()
    .default('contains'),
  priority: integer('priority').notNull().default(0),
  isAutoGenerated: integer('is_auto_generated', { mode: 'boolean' }).notNull().default(false),
  createdAt: text('created_at').notNull(),
});
