export type FileType = 'csv' | 'pdf';
export type MatchType = 'contains' | 'starts_with' | 'regex' | 'exact';

export interface ImportBatch {
  id: string;
  accountId: string;
  fileName: string;
  fileType: FileType;
  transactionCount: number;
  duplicatesSkipped: number;
  importedAt: string;
}

export interface ParsedTransaction {
  date: string;
  amount: number;
  description: string;
  originalDescription: string;
  suggestedCategory?: string;
  isDuplicate?: boolean;
}

export interface ImportPreview {
  fileName: string;
  fileType: FileType;
  transactions: ParsedTransaction[];
  duplicateCount: number;
  columnMapping?: Record<string, string>;
}

export interface ImportResult {
  batchId: string;
  imported: number;
  duplicatesSkipped: number;
}

export interface CategoryRule {
  id: string;
  pattern: string;
  categoryId: string;
  matchType: MatchType;
  priority: number;
  isAutoGenerated: boolean;
  createdAt: string;
  // Joined
  categoryName?: string;
}

export interface CreateCategoryRuleInput {
  pattern: string;
  categoryId: string;
  matchType: MatchType;
  priority?: number;
}
